- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-merge-conflict
    - id: no-commit-to-branch
      args: [--branch, master]
    - id: detect-aws-credentials
      args: ["--allow-missing-credentials"]
    - id: detect-private-key
    - id: flake8
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.3
  hooks:
  -   id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.20
  hooks:
  -   id: isort
